name: luckus7
description: luckus7

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  intl: ^0.17.0
  filesystem_picker: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  filepicker_windows: ^2.0.0
  watcher: ^1.0.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  rxdart: ^0.27.1
  desktop_window: ^0.4.0
  flutter_staggered_grid_view: ^0.4.0
  printing: ^5.2.1
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.6
  android_intent: ^2.0.2
  colorful_safe_area: ^0.3.0
  modal_bottom_sheet: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
