name: com.cushion.lucs
description: lucs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+11

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.6
  intl: ^0.17.0
  filesystem_picker: ^2.0.0-nullsafety.0
  msix: ^2.1.3
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  filepicker_windows: ^2.0.0
  watcher: ^1.0.0
  shared_preferences: ^2.0.6
  new_keyboard_shortcuts: ^0.1.4
  dio: ^4.0.0
  rxdart: ^0.27.1
  desktop_window: ^0.4.0
  flutter_staggered_grid_view: ^0.4.0
  printing: ^5.4.3
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.6
  android_intent: ^2.0.2
  colorful_safe_area: ^0.3.0
  package_info: ^2.0.2
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_crashlytics: ^2.1.1
  flutter_local_notifications: ^6.0.0
  percent_indicator: ^3.0.1
  flutter_animation_progress_bar: ^2.0.1
  fk_user_agent: ^2.0.1
  store_redirect: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1

flutter:
  uses-material-design: true
